###
### Send POST request with json body
POST http://localhost:8080/devices
Content-Type: application/json

{
  "serialNumber": "ccc",
  "macAddress" : "a",
  "qrCode" : "https://q.q",
  "version": "1.0.0"
}


